apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: gopal-cluster 
  region: us-east-2
nodeGroups:
  - name: gdnode
    instanceType: m5.large
    desiredCapacity: 3
    ssh:
      publicKeyName: dockergopal
  - name: scale-east2a
    instanceType: t3.large
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["us-east-2a"]
    iam:
      withAddonPolices:
        autoscaler: true
    labels:
      nodegroup-type: stateful-workload
      instanceType: onDemand
    ssh:
      publicKeyName: dockergopal
  - name: scale-east2b
    instanceType: t3.large
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["us-east-2b"]
    iam:
      withAddonPolices:
        autoscaler: true
    labels:
      nodegroup-type: stateful-workload
      instanceType: onDemand
    ssh:
      publicKeyName: dockergopal
  - name: scale-spot
    desiredCapacity: 1
    maxSize: 10
    instanceDistribution:
      instanceTypes: ["t3.xlarge","t2.xlarge","m5.xlarge"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    availabilityZones: ["us-east-2a","us-east-2b","us-east-2c"]
    iam:
      withAddonPolices:
        autoscaler: true
    labels:
      nodegroup-type: stateful-workload
      instanceType: spot
    ssh:
      publicKeyName: dockergopal
availabilityZones: ["us-east-2a","us-east-2b","us-east-2c"] 
