apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: gopal-cluster 
  region: us-east-2
nodeGroups:
  - name: gdnode
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      publicKeyName: dockergopal
  - name: gd-mixed
    minSize: 3
    maxSize: 5
    instancesDistribution:
      maxPrice: 0.2
      instanceTypes: ["t2.small","t3.small"]
      onDemandPercentageAboveBaseCapacity: 50
    ssh:
      publicKeyName: dockergopal  
