apiVersion: v1
kind: Pod 
metadata:
  name: quota1
spec:
  containers:
  - name: quotacontainer
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"
        
