apiVersion: v1
kind: Pod 
metadata:
  name: quota1
spec:
  containers:
  - name: quotacontainer-2
    image: nginx
    resources:
      limits:
        memory: "1Gi"
        cpu: "800m"
      requests:
        memory: "700Mi"
        cpu: "400m"
        
